// vue-example/src/components/you-are-here.vue
<script setup lang="ts">
import {
  useMap,
  MglPopup,
} from '@indoorequal/vue-maplibre-gl';
import { middleOfUSA } from '@/lib/constants';
import { ref, watchEffect } from 'vue';
import { getLocation } from '@/lib/api';

const coordinates = ref(middleOfUSA);
const mapRef = useMap();

watchEffect(async () => {
  if (!mapRef.isLoaded || !mapRef.map) return;

  const location = await getLocation();
  if (location !== middleOfUSA) {
    coordinates.value = location;
    mapRef.map.flyTo({ center: location, zoom: 8 });
  }
})
</script>
<template>
  <mgl-popup v-if="mapRef.isLoaded" :close-on-click="false" :coordinates="coordinates">
    <h3>You are approximately here!</h3>
  </mgl-popup>
</template>

// react-example/src/components/you-are-here.tsx
import { useEffect, useState } from "react";
import { middleOfUSA } from "../lib/constants";
import { Popup, useMap } from "@vis.gl/react-maplibre";
import { getLocation } from "../lib/api";

export default function YouAreHere() {
  const [popupLocation, setPopupLocation] = useState(middleOfUSA);
  const { current: map } = useMap();

  useEffect(() => {
    if (!map) return;
    (async () => {
      const location = await getLocation();
      if (location !== middleOfUSA) {
        setPopupLocation(location);
        map.flyTo({ center: location, zoom: 8 });
      }
    })();
  }, [map]);

  if (!map) return null;

  return (
    <Popup
      longitude={popupLocation[0]}
      latitude={popupLocation[1]}>
      <h3>You are approximately here!</h3>
    </Popup>
  );
}
